{{- if not .Values.coturn.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-secret
  labels:
{{ include "labels" . | nindent 4}}
data:
  user: {{ printf "%s:%s" .Values.coturn.auth.username .Values.coturn.auth.password | b64enc }}
{{- end }}
