apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coturn.fullname" . }}-coturn-config
  labels:
{{ include "labels" . | nindent 4}}
data:
  turnserver.conf: |
    realm={{.Values.coturn.realm}}

    log-file=stdout
    pidfile=/var/tmp/turnserver.pid
    userdb=/var/tmp/turnserver.db

    # Specify the user for the TURN authentification
    {{if .Values.coturn.authentification.username}}
    # Enable long-term credential mechanism
    lt-cred-mech
    user={{.Values.coturn.authentification.username}}:{{.Values.coturn.authentification.password}}
    {{end}}

    no-cli
    no-tls
    no-dtls
    verbose
    prod
