apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-turn-udp
  annotations:
    {{- range $key, $value := $.Values.service.annotations }}
    "{{ $key }}": "{{ tpl $value $ }}"
    {{- end }}
spec:
  externalTrafficPolicy: {{.Values.service.externalTrafficPolicy}}
  ports:
    - name: turn-udp
      port: {{ .Values.ports.listening }}
      protocol: UDP
      targetPort: {{ .Values.ports.listening }}
    - name: turn-udp-dtls
      port: {{ .Values.ports.tlsListening }}
      protocol: UDP
      targetPort: {{ .Values.ports.tlsListening }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-coturn
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: LoadBalancer