{{- $portRange := untilStep (int .Values.coturn.ports.from) (int (add1 .Values.coturn.ports.to)) 1 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coturn.fullname" . }}-coturn
  labels:
{{ include "labels" . | indent 4}}
spec:
  type: {{ .Values.coturn.service.type }}
  ports:
    - port: 3478
      targetPort: turn-3478
      {{- if eq .Values.coturn.service.type "NodePort" }}
      nodePort: {{default .Values.coturn.service.nodePort 31749}}
      {{- end }}
      protocol: UDP
      name: turn-3478
    {{- range $portRange }}
    - port: {{ . }}
      targetPort: {{ . }}
      {{- if eq $.Values.coturn.service.type "NodePort" }}
      nodePort: {{ . }}
      {{- end }}
      protocol: UDP
      name: turn-udp-{{ . }}
    - port: {{ . }}
      targetPort: {{ . }}
      {{- if eq $.Values.coturn.service.type "NodePort" }}
      nodePort: {{ . }}
      {{- end }}
      protocol: TCP
      name: turn-tcp-{{ . }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "coturn.fullname" . }}-coturn
    app.kubernetes.io/instance: {{ .Release.Name }}