---
replicas: 2

# -- different name for the helm release
nameOverride: ""

service:
  # -- I don't actually know what this is 🤔 open a PR if you know
  externalTrafficPolicy: Local

image:
  # -- container registry and repo for coturn docker image
  repository: "coturn/coturn"
  # -- docker tag for coturn server
  tag: ""
  # -- image pull policy, set to Always if using image.tag: latest
  pullPolicy: IfNotPresent

# -- ref: kubernetes.io/docs/concepts/configuration/manage-resources-containers
resources: {}

# -- Coturn specific labels
labels:
  component: coturn

certificate:
  # -- Enables auto issuing certificates over cert-manager certificates
  # https://cert-manager.io/docs/concepts/certificate/
  enabled: false
  # -- name of secret to create for ssl cert
  secret: "turn-tls"
  # -- name of cert-manager issuer to use for cert generation.
  # change to production issuer when you're stable
  issuerName: "letsencrypt-staging"

externalDatabase:
  # -- enables the use of postgresql instead of the default sqlite
  enabled: true
  # -- Currently only postgresql is supported. mysql coming soon
  type: "postgresql"
  # -- required if externalDatabase.enabled: true and postgresql.enabled: false
  hostname: ""
  # -- username for database, ignored if existingSecret is passed in
  username: ""
  # -- password for database, ignored if existingSecret is passed in
  password: ""
  # -- database to create, ignored if existingSecret is passed in
  database: ""
  # -- name of existing Secret to use for postgresql credentials
  existingSecret: ""
  # Names of the keys in existing secret to use for PostgreSQL credentials
  secretKeys:
    # -- key in existing Secret to use for the db user
    username: ""
    # -- key in existing Secret to use for db user's password
    password: ""
    # -- key in existing Secret to use for the database name
    database: ""
    # -- key in existing Secret to use for the db's hostname
    hostname: ""

# PostgreSQL chart configuration
# see: https://github.com/bitnami/charts/tree/main/bitnami/postgresql
postgresql:
  # -- enables bitnami postgresql subchart, you can disable to use external db
  enabled: true
  global:
    postgresql:
      # -- global.postgresql.auth overrides postgresql.auth
      auth:
        # -- username for database, ignored if existingSecret is passed in
        username: "coturn"
        # -- password for db, autogenerated if empty & existingSecret empty
        password: ""
        # -- database to create, ignored if existingSecret is passed in
        database: "coturn"
        # -- name of existing Secret to use for postgresql credentials
        existingSecret: ""
        # Names of the keys in existing secret to use for PostgreSQL credentials
        # all of these are ignored if existingSecret is empty
        secretKeys:
          # -- key in existingSecret for database to create
          hostname: "hostname"
          # -- key in existingSecret for database to create
          database: "database"
          # -- key in exsiting Secret to use for the coturn user
          username: "username"
          # -- key in existing Secret to use for postgres admin user's password
          adminPasswordKey: "postgresPassword"
          # -- key in existing Secret to use for coturn user's password
          userPasswordKey: "password"

persistence:
  # -- existing PVC to use instead of creating one on the fly
  existingClaim: ""
  # -- annotations for the PVC, ignored if persistence.existingClaim passed in
  annotations: {}
  # -- access mode for the PVC, ignored if persistence.existingClaim passed in
  accessMode: "ReadWriteOnce"
  # -- size of the PVC, ignored if persistence.existingClaim passed in
  size: "1Mi"
  # -- storageClass for the PVC, ignored if persistence.existingClaim passed in
  storageClass: ""

# most coturn config parameters that you really need
coturn:
  # --  hostname for the coturn server realm
  realm: "turn.example.com"

  auth:
    # -- username for the main user of the turn server
    username: "coturn"
    # -- password for the main user of the turn server
    password: ""
    # -- existing secret with keys username/password for coturn
    existingSecret: ""
    secretKeys:
      # -- key in existing secret for turn server user
      username: username
      # -- key in existing secret for turn server user's password
      password: password

  # -- coturn's listening IP address
  listeningIP: "0.0.0.0"

  ports:
    # -- minimum ephemeral port for coturn
    min: 49152
    # -- maximum ephemeral port for coturn
    max: 65535
    # -- insecure listening port
    listening: 3478
    # -- secure listening port
    tlsListening: 5349

  # -- set the logfile. Defaults to stdout for use with kubectl logs
  logFile: "stdout"

  # -- extra configuration for turnserver.conf
  extraTurnserverConfiguration: |
    verbose

# k8s pod security context:
# https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext:
  # -- for all Containers in the Pod, all processes run w/ this userID
  runAsUser: 1000
  # -- for all Containers in the Pod, all processes run w/ this GroupID
  runAsGroup: 1000
  # -- all processes of the container are also part of the supplementary groupID
  fsGroup: 1000
