replicas: 2

service:
  externalTrafficPolicy: Local

image:
  # -- container registry and repo for coturn docker image
  repository: "coturn/coturn"
  # -- docker tag for coturn server
  tag: "{{ .Chart.AppVersion }}"
  pullPolicy: IfNotPresent

resources: { }

# -- Coturn specific labels
labels:
  component: coturn

# -- ports for coturn
ports:
  min: 49152
  max: 65535
  listening: 3478
  tlsListening: 5349

certificate:
  # -- Enables auto issuing certificates over cert-manager certificates
  # https://cert-manager.io/docs/concepts/certificate/
  enabled: true
  # -- REPLACE ME - hostname for ssl cert
  host: "turn.example.com"
  # -- name of secret to create for ssl cert
  secret: "turn-tls"
  # -- name of cert-manager issuer to use for cert generation
  issuerName: "letsencrypt"

config:
  auth:
    # -- not working: existing secret with keys username/password for coturn
    existingSecret: ""
  turnserver: |
    realm={{ .Values.certificate.host }}
    listening-ip=0.0.0.0
    listening-port={{ .Values.ports.listening }}
    tls-listening-port={{ .Values.ports.tlsListening }}
    min-port={{ .Values.ports.min }}
    max-port={{ .Values.ports.max }}
    log-file=stdout
    verbose
    pidfile=/var/tmp/turnserver.pid
    lt-cred-mech
    pkey=/tls/tls.key
    cert=/tls/tls.crt
