imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

coturn:
  realm: "iits-consulting.de"
  traefik:
    tcp:
      enabled: true
      entrypoint: coturn-tcp
      routeMatch: "HostSNI(`*`)"
      terminationDelay: 3600
    udp:
      enabled: false
      entrypoint: coturn-udp
  kind: Deployment
  service:
    type: ClusterIP

  authentification:
    username: coturn
    password: "coturn12345"

  image:
    repository: "instrumentisto/coturn"
    tag: "4.5.1.3"
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources: { }

  # Coturn specific labels
  labels:
    component: coturn
