imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

coturn:
  traefik:
    tcp:
      enabled: true
      entrypoint: coturn-tcp
      routeMatch: "HostSNI(`*`)"
      terminationDelay: 3600
    udp:
      enabled: false
      entrypoint: coturn-udp
  kind: Deployment
  service:
    type: ClusterIP

  image:
    repository: "instrumentisto/coturn"
    tag: "4.5.1.3"
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources: { }

  # Coturn specific labels
  labels:
    component: coturn
  config: |
    realm=turn-domain.de

    log-file=stdout
    pidfile=/var/tmp/turnserver.pid
    userdb=/var/tmp/turnserver.db

    # Specify the user for the TURN authentification
    # Enable long-term credential mechanism
    lt-cred-mech
    user=Username:Password

    no-cli
    no-tls
    no-dtls
    verbose
    prod
