{{- if .Values.coturn.traefik.udp.enabled}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{.Release.Name}}-udp
spec:
  entryPoints:
    - {{.Values.coturn.traefik.udp.entrypoint}}
  routes:
    - services:
        - name: {{ include "coturn.fullname" . }}-coturn
          terminationDelay: {{.Values.coturn.traefik.tcp.terminationDelay}}
          weight: 1000
          port: 3478
{{- end}}
