name: Lint Charts

on:
  push:
    branches:
      - '!main'
    paths-ignore:
      - '.github/**'
      - 'LICENSE'
      - 'README.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3.5

      - name: Lint chart
        run: helm lint charts/* --strict
